# fly.toml file generated for falling-dew-7859 on 2023-03-08T15:45:01-07:00
# Updated Oct 22, 2024

app = "falling-dew-7859"
primary_region = 'ord'

[build]

[env]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
